/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    ActivityFeed: typeof import('./src/components/user/home/ActivityFeed.vue')['default']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    Announcements: typeof import('./src/components/user/home/Announcements.vue')['default']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Banner: typeof import('./src/components/user/home/Banner.vue')['default']
    ChallengeCard: typeof import('./src/components/user/training/ChallengeCard.vue')['default']
    Challenges: typeof import('./src/components/user/training/Challenges.vue')['default']
    CheckIn: typeof import('./src/components/user/home/CheckIn.vue')['default']
    Header: typeof import('./src/components/user/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/user/home/Sidebar.vue')['default']
  }
}
